[coordinates] NoClassDefFoundError for SolrParams
Caused by our recent restructuring and incomplete headers in the SolrJ
bundle from Orbit (see Bug 413496).

Bug: 413496
Change-Id: Ic4b26d77b4832a593d4fd19573dc32fe65a13958
Signed-off-by: Andreas Sewe <andreas.sewe@codetrails.com>